{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "26643562_4eba5e52",
        "filename": "lib/pel_utils.py",
        "patchSetId": 56
      },
      "lineNbr": 325,
      "author": {
        "id": 1000358
      },
      "writtenOn": "2022-12-14T14:18:27Z",
      "side": 1,
      "message": "return is not required after raising exception. It will not be executed.",
      "range": {
        "startLine": 325,
        "startChar": 8,
        "endLine": 325,
        "endChar": 14
      },
      "revId": "d1298f4f106cec4fec12bba4e55c961b4a0f55cb",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}