{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "4cd0e3c7_75c38b07",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1000053
      },
      "writtenOn": "2023-01-13T05:19:54Z",
      "side": 1,
      "message": "what is causing max connection_count issue \u0026 how this will resolve max connection_count issue?",
      "revId": "ef765bbb31cd93ad30119c0054ea5686fff8a545",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}